headless = true
quit_on_end = true
valid_path_names = [ "path", "filename", "video", "video_path",]
valid_descriptions = [ "description", "desc", "caption",]
implicit_wait = 5
explicit_wait = 60
uploading_wait = 180
supported_file_types = [ "mp4", "mov", "avi", "wmv", "flv", "webm", "mkv", "m4v", "3gp", "3g2", "gif",]
max_description_length = 150
platform = "douyin"

[schedule]
upload_time = [ 9, 15, 19, 12,22]

[crawler]
#douyin
direct_douyin_link = "https://www.douyin.com/video/7470498918543936804"
xbutton = "//div[@class='douyin-login__close dy-account-close']"
direct_douyin_path = "//*[@id=\"douyin-right-container\"]/div[2]/div/div/div[1]/div[2]/div/xg-video-container/video"
next_video_douyin = "//*[@id=\"douyin-right-container\"]/div[2]/div/div/div[1]/div[2]/div/div[2]/div[1]/div/div/div[2]"

#tiktok BETA!!
direct_tiktok_link = "https://www.tiktok.com/@malgbaisi_/video/7460533837437619464?q=techtok&t=1739799180710"
direct_tiktok_path = '//*[@id="xgwrapper-4-7460533837437619464"]/video'
next_video_tiktok = '//*[@id="main-content-video_detail"]/div/div[2]/div[1]/div[1]/div[1]/div[4]/div[1]/button[2]'
close_captcha = '//*[@id="captcha_close_button"]'


jumlah_stok_video = 6


[file_management]
video_name_length = 5

[paths]
main = "https://www.tiktok.com/"
login = "https://www.tiktok.com/login/phone-or-email/email"
upload = "https://www.tiktok.com/creator-center/upload?lang=en"

[disguising]
user_agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3"

[selectors.login]
username_field = "//input[@name=\"username\"]"
password_field = "//input[@type=\"password\"]"
login_button = "//button[@type=\"submit\"]"
alert_user_if_failed = true
cookie_of_interest = "sessionid"

[selectors.upload]
iframe = "//iframe"
split_window = "//button[./div[text()='Not now']]"
upload_video = "//input[@type='file']"
upload_finished = "//div[contains(@class, 'btn-cancel')]"
upload_confirmation = "//div[@title]"
process_confirmation = "//div[contains(@class, 'cover-selector-image-container')]/img[contains(@class, 'cover-selector-image')]"
description = "//div[@contenteditable='true']"
visibility = "//div[@class='tiktok-select-selector']"
options = [ "Public", "Friends", "Private",]
mention_box = "//div[contains(@class, 'mention-list-popover')]"
mention_box_user_id = "//span[contains(@class, 'user-id')]"
comment = "//label[.='Comment']/following-sibling::div/input"
duet = "//label[.='Duet']/following-sibling::div/input"
stitch = "//label[.='Stitch']/following-sibling::div/input"
post = "//button[@data-e2e='post_video_button']"
post_confirmation = "//div[contains(@class, 'tiktok-modal__modal-wrapper')]//div[contains(@class, 'tiktok-modal__modal-title') and contains(text(), 'Your videos are being posted to TikTok!')]"

[selectors.schedule]
switch = "//*[@id='tux-3']"
date_picker = "//div[contains(@class, 'date-picker-input')]"
calendar = "//div[contains(@class, 'calendar-wrapper')]"
calendar_month = "//span[contains(@class, 'month-title')]"
calendar_valid_days = "//div[@class='jsx-4172176419 days-wrapper']//span[contains(@class, 'day') and contains(@class, 'valid')]"
calendar_arrows = "//span[contains(@class, 'arrow')]"
time_picker = "//div[contains(@class, 'time-picker-input')]"
time_picker_text = "//div[contains(@class, 'time-picker-input')]/*[1]"
time_picker_container = "//div[@class='tiktok-timepicker-time-picker-container']"
timepicker_hours = "//span[contains(@class, 'tiktok-timepicker-left')]"
timepicker_minutes = "//span[contains(@class, 'tiktok-timepicker-right')]"

[selectors.upload.cookies_banner]
banner = "tiktok-cookie-banner"
button = "div.button-wrapper"
